#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Jan 25 20:43:32 EST 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim aluTB_time_synth -key {Post-Synthesis:sim_1:Timing:aluTB} -tclbatch aluTB.tcl -view /home/Sol/CMPE-260-Digital-System-Design-II/alu4/aluTB_time_synth.wcfg -log simulate.log"
xsim aluTB_time_synth -key {Post-Synthesis:sim_1:Timing:aluTB} -tclbatch aluTB.tcl -view /home/Sol/CMPE-260-Digital-System-Design-II/alu4/aluTB_time_synth.wcfg -log simulate.log

